# Generated by Django 4.1.2 on 2022-11-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enroll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="skill",
            field=models.CharField(
                choices=[
                    ("python", "python"),
                    ("react", "react"),
                    ("java", "java"),
                    ("javascript", "javascript"),
                ],
                default=34,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
