# Generated by Django 4.1.2 on 2022-11-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_alter_student_student_id_alter_teacher_teacher_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="school.teacher"
            ),
        ),
    ]
