# Generated by Django 4.1.2 on 2022-11-21 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_alter_student_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.teacher",
            ),
        ),
    ]
