# Generated by Django 4.1.2 on 2022-11-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enroll", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="stuemail",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="stuname",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="stupass",
        ),
    ]
